BIEN_SO_MAP_DAU = {
    "11": "Cao Bằng",
    "12": "Lạng Sơn",
    "14": "Quảng Ninh",
    "99": "Bắc Ninh", "98": "Bắc Ninh",
    "22": "Tuyên Quang", "23": "Tuyên Quang",
    "24": "Lào Cai", "21": "Lào Cai",
    "25": "Lai Châu",
    "27": "Điện Biên",
    "26": "Sơn La",
    "20": "Thái Nguyên", "97": "Thái Nguyên",
    "19": "Phú Thọ", "28": "Phú Thọ", "88": "Phú Thọ",
    "29": "Hà Nội", "30": "Hà Nội", "31": "Hà Nội", "32": "Hà Nội", "33": "Hà Nội", "40": "Hà Nội",
    "15": "Hải Phòng", "16": "Hải Phòng", "34": "Hải Phòng",
    "89": "Hưng Yên", "17": "Hưng Yên",
    "35": "Ninh Bình", "18": "Ninh Bình", "90": "Ninh Bình",
    "36": "Thanh Hoá",
    "37": "Nghệ An",
    "38": "Hà Tĩnh",
    "74": "Quảng Trị", "73": "Quảng Trị",
    "75": "TP Huế",
    "43": "Đà Nẵng", "92": "Đà Nẵng",
    "76": "Quảng Ngãi", "82": "Quảng Ngãi",
    "81": "Gia Lai", "77": "Gia Lai",
    "47": "Đắk Lắk", "78": "Đắk Lắk",
    "79": "Khánh Hoà", "85": "Khánh Hoà",
    "49": "Lâm Đồng", "48": "Lâm Đồng", "86": "Lâm Đồng",
    "60": "Đồng Nai", "39": "Đồng Nai", "93": "Đồng Nai",
    "41": "TP Hồ Chí Minh", "50": "TP Hồ Chí Minh",
    "51": "TP Hồ Chí Minh", "52": "TP Hồ Chí Minh",
    "53": "TP Hồ Chí Minh", "54": "TP Hồ Chí Minh",
    "55": "TP Hồ Chí Minh", "56": "TP Hồ Chí Minh",
    "57": "TP Hồ Chí Minh", "58": "TP Hồ Chí Minh",
    "59": "TP Hồ Chí Minh", "61": "TP Hồ Chí Minh",
    "62": "Tây Ninh", "70": "Tây Ninh",
    "66": "Đồng Tháp", "63": "Đồng Tháp",
    "65": "Cần Thơ", "83": "Cần Thơ", "95": "Cần Thơ",
    "64": "Vĩnh Long", "71": "Vĩnh Long", "84": "Vĩnh Long",
    "69": "Cà Mau", "94": "Cà Mau",
    "68": "An Giang", "67": "An Giang",
    "80": "Cục CSGT"
}
